version: "3"
services:
  redis:
    image: redis:5.0-rc5-alpine
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
  mysql:
    image: mysql:5.7
    restart: on-failure
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: America/Sao_Paulo
    ports:
      - 3306:3306
volumes:
  redis_data:
  mysql_data:
